[phases.setup]
nixPkgs = ["...", "python3", "python311Packages.pip", "msttcorefonts-installer"]

[phases.build]
cmds = ["npm install", "pip install pdf2docx --break-system-packages"]

[start]
cmd = "npm start"
